/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        thangam: {
          wine: '#7A1F3D',
          maroon: '#5A1426',
          'soft-burgundy': '#8B3A4E',
          'deepest-burgundy': '#3B0D18',
          burgundy: {
            DEFAULT: '#6E1830',
            primary: '#6E1830',
            deep: '#4A0E1B',
            wine: '#7A1F3D',
            maroon: '#5A1426',
            soft: '#8B3A4E',
            deepest: '#3B0D18',
            darkest: '#3B0D18',
          },
          cream: {
            DEFAULT: '#F7F0E4',
            primary: '#F7F0E4',
            dark: '#1F161A',
            bright: '#FFF8ED',
            light: '#FFF8ED',
            offwhite: '#FFFDF8',
            muted: '#EFE7D8',
          },
          'cream-dark': '#1F161A',
          'cream-bright': '#FFF8ED',
          'cream-light': '#FFF8ED',
          'cream-offwhite': '#FFFDF8',
          'cream-muted': '#EFE7D8',
          text: {
            DEFAULT: '#1F161A',
            dark: '#1F161A',
            cream: '#FFF8ED',
            creamMuted: '#F7F0E4',
          },
          gold: {
            DEFAULT: '#C6A15B',
            light: '#E0C078',
            dark: '#9E7B35',
            400: '#E0C078',
            500: '#C6A15B',
            600: '#9E7B35',
          },
          'gold-light': '#E0C078',
          'gold-dark': '#9E7B35',
          whatsapp: '#25D366',
        },
        'thangam-wine': '#7A1F3D',
        'thangam-maroon': '#5A1426',
        'thangam-soft-burgundy': '#8B3A4E',
        'thangam-deepest-burgundy': '#3B0D18',
        'thangam-cream': '#F7F0E4',
        'thangam-cream-dark': '#1F161A',
        'thangam-cream-bright': '#FFF8ED',
        'thangam-gold': '#C6A15B',
        'thangam-gold-light': '#E0C078',
        'thangam-gold-dark': '#9E7B35',
        'thangam-whatsapp': '#25D366',
      },
      fontFamily: {
        serif: ['"Cormorant Garamond"', 'Playfair Display', '"Noto Serif Tamil"', 'Georgia', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'Inter', '"Mukta Malar"', 'system-ui', '-apple-system', 'sans-serif'],
        tamil: ['"Noto Serif Tamil"', '"Mukta Malar"', 'serif'],
      },
      boxShadow: {
        'gold-sm': '0 0 10px rgba(212, 175, 55, 0.15)',
        'gold-md': '0 0 20px rgba(212, 175, 55, 0.25)',
        'gold-lg': '0 0 30px rgba(212, 175, 55, 0.35)',
        'card-dark': '0 8px 30px rgba(0, 0, 0, 0.4)',
      },
      borderRadius: {
        'luxury': '8px',
        'luxury-lg': '14px',
      },
      maxWidth: {
        'site': '1280px',
      },
    },
  },
  plugins: [],
}
